# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5aae8c30f3acdd4ce614804d0129114d66725bee4674ee88e555ebe0653cc0ddfcf14acc2a39e9297aee505242dfab39ea59296c8fc841076533c800f75e153

test:
  secret_key_base: d36d23911eade6d9c63c9fd8804073ad230ec3e34efc06ee5b1d938421fba00980583204ce9f85fb9c068fec914ad12a3664221bd7baf1f9f180a0e52843ddc7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
